const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {prepare}=require('../scripts/catalog-update.cjs');
const root=path.resolve(__dirname,'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const recipes=read('data/recipes.json'),products=read('data/products.json'),patch=read('catalog-drafts/2026-10-04.json');
const clone=x=>JSON.parse(JSON.stringify(x));
const base=clone(recipes),published=clone(products);
Object.keys(base).forEach(type=>base[type]=base[type].filter(r=>!patch.recipes[type].some(p=>p.id===r.id)));
published.products=published.products.filter(p=>!patch.products.some(x=>x.id===p.id));
const first=prepare(base,published,patch);
assert.equal(first.changes.filter(x=>x.action==='add').length,12);
const again=prepare(first.recipes,first.products,patch);
assert(again.changes.every(x=>x.action==='unchanged'));
assert.deepEqual(again.recipes,first.recipes);assert.deepEqual(again.products,first.products);
Object.keys(base).forEach(type=>base[type].forEach(r=>assert.deepEqual(first.recipes[type].find(x=>x.id===r.id),r)));
let bad=clone(patch);bad.products[0].id='accidental-duplicate';assert.throws(()=>prepare(first.recipes,first.products,bad),/duplicate/i);
bad=clone(patch);bad.products[0].rating=5;assert.throws(()=>prepare(base,published,bad),/Personal data/);
bad=clone(patch);bad.personal={};assert.throws(()=>prepare(base,published,bad),/private/);
bad=clone(patch);bad.format='barista-backup';assert.throws(()=>prepare(base,published,bad),/personal backup/);
bad=clone(patch);bad.products[0].recipeIds=['missing'];assert.throws(()=>prepare(base,published,bad),/missing/);
bad=clone(patch);bad.recipes.tea[0].methods[0].tea=0;assert.throws(()=>prepare(base,published,bad));
assert.equal(patch.products.length,6);assert.equal(new Set(patch.products.map(p=>p.id)).size,6);
const tea=id=>patch.recipes.tea.find(r=>r.id===id);
assert.deepEqual(['rishi-hibiscus-berry','rishi-english-breakfast','rishi-earl-grey-supreme'].map(id=>[tea(id).tea,tea(id).water,tea(id).temp,tea(id).steeps[0]]),[[11,350,93,300],[10,350,93,240],[9,350,93,240]]);
['tezumi-kanoyama','tezumi-umezuki'].forEach(id=>{const r=tea(id);assert.equal(r.tea,2);assert.equal(r.water,70);assert.equal(r.temp,70);assert.equal(r.methods[0].vessel,'chawan');assert.equal(r.steeps.length,0);});
assert.equal(patch.recipes.drinks[0].ingredients.find(i=>i.name.startsWith('Karak')).unit,'mL');
console.log('PASS: purchase patch validation, six identities, exact vendor parameters, duplicate detection, idempotent reruns, existing catalog preservation, private-data rejection and broken-reference rejection.');
// Second real-world workflow run: one multi-bag coffee order, not shipping notices.
const coffeePatch=read('catalog-drafts/2026-10-04-tim-wendelboe.json');
const coffeeBase=clone(recipes),coffeeProducts=clone(products);
coffeeBase.coffee=coffeeBase.coffee.filter(r=>!coffeePatch.recipes.coffee.some(x=>x.id===r.id));
coffeeProducts.products=coffeeProducts.products.filter(p=>!coffeePatch.products.some(x=>x.id===p.id));
const coffeeFirst=prepare(coffeeBase,coffeeProducts,coffeePatch);
assert.equal(coffeeFirst.changes.filter(x=>x.action==='add').length,12);
assert.equal(coffeePatch.products.length,6);
assert.deepEqual(coffeePatch.products.map(p=>p.country),['El Salvador','Colombia','Ethiopia','Kenya','Kenya','Honduras']);
assert(coffeePatch.products.every(p=>p.processing==='Washed'&&p.brand==='Tim Wendelboe'));
const coffeeAgain=prepare(coffeeFirst.recipes,coffeeFirst.products,coffeePatch);
assert(coffeeAgain.changes.every(x=>x.action==='unchanged'));
assert.deepEqual(coffeeAgain,prepare(coffeeAgain.recipes,coffeeAgain.products,coffeePatch));
assert.deepEqual(coffeeFirst.recipes.tea,coffeeBase.tea);
coffeeBase.coffee.forEach(r=>assert.deepEqual(coffeeFirst.recipes.coffee.find(x=>x.id===r.id),r));
console.log('PASS: second purchase workflow, six coffee products, correct origins, repeated application, and preservation of teas and original coffee templates.');
